"""set null on delete for lessons.subject_id

Revision ID: 00889a25b50f
Revises: 92be77ee68e9
Create Date: 2025-10-24 08:11:32.916042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00889a25b50f'
down_revision: Union[str, None] = '92be77ee68e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grades', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('grades_subject_id_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_subject_id_fkey', 'grades', 'subjects', ['subject_id'], ['id'])
    op.alter_column('grades', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
