"""set null on delete for lessons.teacher_id

Revision ID: 088c9ca0b1b4
Revises: ae1fa51dddbc
Create Date: 2025-10-24 08:07:25.836000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088c9ca0b1b4'
down_revision: Union[str, None] = 'ae1fa51dddbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lessons_teacher_id_fkey', 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key('lessons_teacher_id_fkey', 'lessons', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
