"""set null on delete for lessons.room_id

Revision ID: 2abb77daac61
Revises: b9c679060cfc
Create Date: 2025-10-24 08:15:58.350172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abb77daac61'
down_revision: Union[str, None] = 'b9c679060cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lessons_room_id_fkey', 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key('lessons_room_id_fkey', 'lessons', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
