"""set null on delete for grades.teacher_id

Revision ID: 92be77ee68e9
Revises: 088c9ca0b1b4
Create Date: 2025-10-24 08:09:29.301606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92be77ee68e9'
down_revision: Union[str, None] = '088c9ca0b1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('grades_teacher_id_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'teachers', ['teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_teacher_id_fkey', 'grades', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
