"""fix ondelete for subjects.primary_teacher_id

Revision ID: ae1fa51dddbc
Revises: c70abca5a899
Create Date: 2025-10-24 08:06:02.538868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1fa51dddbc'
down_revision: Union[str, None] = 'c70abca5a899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subjects_primary_teacher_id_fkey', 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'teachers', ['primary_teacher_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key('subjects_primary_teacher_id_fkey', 'subjects', 'teachers', ['primary_teacher_id'], ['id'])
    # ### end Alembic commands ###
