"""set null on delete for lessons.subject_id

Revision ID: b9c679060cfc
Revises: 00889a25b50f
Create Date: 2025-10-24 08:14:30.682248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c679060cfc'
down_revision: Union[str, None] = '00889a25b50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lessons', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_lessons_subject_id'), 'lessons', ['subject_id'], unique=False)
    op.drop_constraint('lessons_subject_id_fkey', 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key('lessons_subject_id_fkey', 'lessons', 'subjects', ['subject_id'], ['id'])
    op.drop_index(op.f('ix_lessons_subject_id'), table_name='lessons')
    op.alter_column('lessons', 'subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
